OrdererOrgs:
- Name: OrdererOrg
  Domain: orderer-org
  CommonName: orderer-org
  Specs:
  - Hostname: orderer0
    CommonName: "{{.Hostname}}"
PeerOrgs:
- Name: CompnayAOrg
  Domain: compnay-a-org
  Specs:
  - Hostname: compnay-a-peer-a
    CommonName: "{{.Hostname}}"
  - Hostname: compnay-a-peer-b
    CommonName: "{{.Hostname}}"
- Name: CompnayBOrg
  Domain: compnay-b-org
  Specs:
  - Hostname: compnay-b-peer-a
    CommonName: "{{.Hostname}}"
  - Hostname: compnay-b-peer-b
    CommonName: "{{.Hostname}}"
